Homework-2 ready
TheDedEgor/java-course pull request #2
Opened 2023-10-13 14:49 UTC by TheDedEgor

2023-10-18 22:58 UTC, kkmikhaylova requested changes

2023-10-18 22:58 UTC, kkmikhaylova commented on src/main/java/edu/hw2/task2/Rectangle.java
> +    public final int getWidth() {
А где методы `setWidth`, `setHeight`?

2023-10-18 22:58 UTC, kkmikhaylova commented on src/main/java/edu/hw2/task3/FaultyConnection.java
> +        var num = rand.nextInt(0, 100);
Повторяется код с рандомом, лучше вынести в одно место. И вместе supress можно вынести значения в static переменные

2023-10-18 22:58 UTC, kkmikhaylova commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +                conn.execute(command);
Соединение нужно закрыть

2023-10-18 22:58 UTC, kkmikhaylova commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +        Throwable error = null;
Предложила бы сменить название переменной, так как слово Error здесь может запутать (error это наследник throwable)

2023-10-18 23:15 UTC, TheDedEgor commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +                conn.execute(command);
Здесь используется try with resources. Он автоматически закрывает соединение.

2023-10-18 23:19 UTC, TheDedEgor commented on src/main/java/edu/hw2/task2/Rectangle.java
> +    public final int getWidth() {
Задание немного странное и в нем же не указано, что нельзя убирать методы или модифицировать существующие классы. А по заданию код удовлетворяет всем ограничениям.

2023-10-18 23:54 UTC, kkmikhaylova commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +                conn.execute(command);
Точно. Кажется пора спать 😆

2023-10-18 23:59 UTC, kkmikhaylova commented on src/main/java/edu/hw2/task2/Rectangle.java
> +    public final int getWidth() {
С текущим подходом у тебя нет возможности написать тест из задания as is, хотелось бы его видеть в итоговом наборе проверок. И мы в таком случае не разрешаем парадокс, а просто избавляемся от него

2023-10-22 19:48 UTC, kkmikhaylova approved these changes

2023-10-22 22:11 UTC, merged