Homework-3 ready
TheDedEgor/java-course pull request #4
Opened 2023-10-23 20:05 UTC by TheDedEgor

2023-11-07 17:27 UTC, Desire456 requested changes

2023-11-07 17:27 UTC, Desire456 commented on src/main/java/edu/hw3/Task1.java
> +        var alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
Нужно вынести в константы

2023-11-07 17:27 UTC, Desire456 commented on src/test/java/edu/hw3/AtbashTest.java
> +public class AtbashTest {
Воспользуйся параметризированными тестами -  https://www.baeldung.com/parameterized-tests-junit-5

2023-11-07 17:27 UTC, Desire456 commented on src/test/java/edu/hw3/AtbashTest.java
> +    void Test1() {
Названия методов в java - строго с маленькой буквы + название в виде `test1`, `test2` и т.д. - плохо, нужны более детализированные названия

2023-11-07 17:27 UTC, Desire456 commented on src/test/java/edu/hw3/ClusterizeTest.java
> +public class ClusterizeTest {
Смотри замечания для `AtbashTest`

2023-11-07 17:27 UTC, Desire456 commented on src/main/java/edu/hw3/Task3.java
> +        }
Можно написать в одну строчку, используя один прекрасный метод интерфейса `Map` :) А можно вообще через Stream API в 2 метода.

2023-11-07 17:27 UTC, Desire456 commented on src/test/java/edu/hw3/FreqDictTest.java
> +public class FreqDictTest {
Смотри замечания из `AtbashTest`

2023-11-07 17:27 UTC, Desire456 commented on src/main/java/edu/hw3/Task4.java
> +    public static String convertToRoman(Integer num) {
Очень элегентно решил через `TreeMap`, молодец! :)

2023-11-07 17:27 UTC, Desire456 commented on src/main/java/edu/hw3/Task4.java
> +        map.put(1, "I");
Вынести в константы

2023-11-07 17:27 UTC, Desire456 commented on src/main/java/edu/hw3/ContactsComparator.java
> +    }
Для того чтобы посортировать в обратную сторону, достаточно воспользоваться методом `reversed()` или передать значения в `compare` наоборот.

2023-11-07 17:27 UTC, Desire456 commented on src/main/java/edu/hw3/ContactsComparator.java
> +    public int compare(String o1, String o2) {
Давай лучше тут сравнивать объекты контрактов (их нужно создать до этого). Это не ответственность компаратора создавать объекты.

2023-11-07 17:27 UTC, Desire456 commented on src/main/java/edu/hw3/ContactsComparator.java
> +        }
Ты ведь сравниваешь 2 строки, попробуй сделать так, чтобы тебе пришлось вызвать `compareTo` единожды)

2023-11-07 17:27 UTC, Desire456 commented on src/main/java/edu/hw3/Task5.java
> +        return list.stream().sorted(comparator).map(item -> (Object) item).toList();
От того что ты тут скастил строки к объектам, ничего не изменилось, это все еще строки :)

2023-11-07 17:27 UTC, Desire456 commented on src/main/java/edu/hw3/Task5.java
> +    public static List<Object> parseContacts(List<String> list, String sortDirection) {
Если сделаешь `sortDirection` перечислением - избавишь себя от кучи проблем

2023-11-07 17:27 UTC, Desire456 commented on src/main/java/edu/hw3/Stock.java
> +        return price.compareTo(o.price);
Выходит так, что у тебя сортировка обратная заданию, но потом ты используешь `reversedOrder`. Почему сразу не сортировать как сказано в задании?

2023-11-07 17:27 UTC, Desire456 commented on src/main/java/edu/hw3/Task7.java
> +    public int compare(String o1, String o2) {
```
var map = new TreeMap<String, String>(new Task7());
        map.put(null, "a");
        map.put("1", "a");
        map.put("2", "a");
        map.put(null, "a");
        map.put("3", "a");
        System.out.println(map);
```

Код выше выведет две пары с ключом `null`, что не совсем корректно

2023-11-07 17:27 UTC, Desire456 commented on src/main/java/edu/hw3/Task8.java
> +public class Task8<T> implements Iterator<T> {
Решение рабочее. Но хотелось бы, чтобы ты не пользовался другим итератором)

2023-11-08 08:31 UTC, Desire456 commented on src/main/java/edu/hw3/ContactsComparator.java
> +        if (!p1.getSurname().isEmpty() && !p2.getSurname().isEmpty()) {
А если у одного есть фамилия, а у второго нет?

2023-11-08 08:40 UTC, TheDedEgor commented on src/main/java/edu/hw3/ContactsComparator.java
> +        if (!p1.getSurname().isEmpty() && !p2.getSurname().isEmpty()) {
Ой, забыл на 'или' поменять

2023-11-08 20:37 UTC, merged